language: java

jdk:
  - oraclejdk8

script:
  - "mvn clean package"

deploy:
  provider: openshift
  edge:
    branch: openshift-deps
  # Configure these values on your TravisCI 'Repository Settings' page:
  # http://docs.travis-ci.com/user/environment-variables/#Using-Settings
  user: $EMAIL_ADDRESS
  password:
    secure: bDdymgK1dThw7m2cWQE4ajHz/aTrbb6lCBmrEWEosSN1aMq3b9FRABdLleQ9+4tT+RuGBqngwqnaP9JeX2aEPvGFOVPpAunsTVAoBK4dJulmfMdDC29dyIt/P4pn0RIIpARyQu7Y+BEqYgPttDWgJBGE1WanpjnpuU6B9eCgGQ/UhkZe5FNpFQMknOFp+yhgpKKqEBGcQ5xga5so9kKmmb3y9hld+KqmwTM0hfhfCR+AfouOClFD2r5gO2zTEEuYouuvo4TFySNvuwIowrflVgR6a5t1PC+xl7vAxb2A7D1NTjjo2/hpg1AAs4X07TWYP49E0cEZqInTkLP0s+MSN5PUbk56SpeynkmHs/WdipHrQsZu72Fb7+biOVp/3DMh6g+UvalUPgfTvs8/bJmIHBq6QbkS+XUqZqhOmSwCAqz8J/6ZpBJfjcDXyYZ1e46rvi1Ra6+qjaQSaXWF8gbdOMsHPAssDNnMYxVxQ7oxTTCaEP7+CFKYbeY+7ayR6NB9rFjH0EyoMMH2zCqjsN1it8cgENkCh8Yd1BCTCbgbOJzR+EMJ72qdXm5lXXI4jVkCrpHAL8Lr7nRe8ekICrfWHrEKPRPr3s50dTa83V8WiOuqZ0NzpGqercCw4PluBL78ExRrP2vpYdipPyusW6sH9M6xv5EKy646SMm8U/xv1Wc=
  app: $APP_NAME
  domain: $DOMAIN_NAME
  on:
    repo: akrystian/jvmVideo
  skip_cleanup: true
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "[[ $TRAVIS_BRANCH == 'master' ]] && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONAR_TOKEN}"
  - "[[ $TRAVIS_BRANCH == 'master' ]] && git config --global user.email 'travis@localhost.localdomain' && git config --global user.name 'Travis CI' && git add --all && git commit -am 'Travis change'"

