mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: mysql
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql

elasticsearch:
  image: elasticsearch:2.4.6
  ports:
    - "9200:9200"
    - "9300:9300"